1. 这个是介绍numpy如何对高纬度矩阵求和，求均值
2. 模拟的场景就是一年有12各月的一个nc维度数据

In [1]:
import numpy as np
from tqdm import tqdm

In [7]:
rawdata = np.random.randint(low=0, high=300, size=(12, 360, 720)).astype('float64')
rawdata.shape

(12, 360, 720)

In [8]:
np.mean(rawdata, axis=0).shape

(360, 720)

In [15]:
rawdata[0, 0, 0] = np.nan

In [17]:
rawdata

array([[[ nan, 158., 261., ...,  69., 286., 113.],
        [ 62., 147., 125., ..., 261., 165., 208.],
        [287.,  68., 146., ..., 160.,  90., 179.],
        ...,
        [292.,  49.,  72., ..., 248.,  88., 249.],
        [204.,   2., 210., ...,  36.,  91., 101.],
        [221., 120., 229., ...,  81., 113.,  90.]],

       [[ 31., 120., 217., ..., 280.,  65.,  60.],
        [114., 292., 140., ..., 249., 246., 255.],
        [ 58.,  17., 171., ..., 285.,  60.,   2.],
        ...,
        [188.,  66.,  25., ..., 134., 290.,  87.],
        [ 64., 243., 234., ..., 292., 117., 190.],
        [258., 299.,  73., ...,  71., 237., 135.]],

       [[ 76., 223., 274., ..., 130., 219., 293.],
        [ 23., 221., 221., ..., 109.,  11.,  35.],
        [112., 237.,  67., ..., 138., 297., 288.],
        ...,
        [287.,  10., 121., ..., 216., 149., 155.],
        [ 46.,  17., 117., ..., 223., 225.,  84.],
        [ 25., 161., 286., ..., 138., 238., 228.]],

       ...,

       [[166., 272., 243

In [18]:
np.mean(rawdata, axis=0)


array([[         nan, 148.91666667, 209.25      , ..., 133.        ,
        144.83333333, 165.5       ],
       [ 90.16666667, 184.33333333, 169.83333333, ..., 158.66666667,
        116.25      , 146.5       ],
       [167.91666667, 135.41666667, 121.41666667, ..., 167.25      ,
        177.        , 168.        ],
       ...,
       [164.41666667, 121.5       , 145.58333333, ..., 195.33333333,
        149.41666667, 163.41666667],
       [160.33333333, 136.33333333, 185.08333333, ..., 157.08333333,
        153.16666667, 111.        ],
       [204.25      , 160.91666667, 126.5       , ..., 179.75      ,
        175.41666667, 153.08333333]])

In [19]:
np.nanmean(rawdata, axis=0)


array([[112.09090909, 148.91666667, 209.25      , ..., 133.        ,
        144.83333333, 165.5       ],
       [ 90.16666667, 184.33333333, 169.83333333, ..., 158.66666667,
        116.25      , 146.5       ],
       [167.91666667, 135.41666667, 121.41666667, ..., 167.25      ,
        177.        , 168.        ],
       ...,
       [164.41666667, 121.5       , 145.58333333, ..., 195.33333333,
        149.41666667, 163.41666667],
       [160.33333333, 136.33333333, 185.08333333, ..., 157.08333333,
        153.16666667, 111.        ],
       [204.25      , 160.91666667, 126.5       , ..., 179.75      ,
        175.41666667, 153.08333333]])