### 统计某个维度上的nan数量
1. [文章详细介绍](https://mp.weixin.qq.com/s?__biz=MzU3MDkzNjk1OQ==&mid=2247491192&idx=1&sn=15a774ed22a5347fa7ac6d9db8cb7125&chksm=fce68568cb910c7ed4a784414c4d3c438ec83f9d71b2509e537c60d154661c49b435dafc9287&token=1553435301&lang=zh_CN#rd)

In [1]:
import numpy as np 

In [2]:
arr = np.array([[[5, np.nan, np.nan, 7, 2],
                 [3, np.nan, 1, 8, np.nan],
                 [4, 9, 6, np.nan, np.nan]],
                [[5, np.nan, np.nan, 7, 2],
                 [3, np.nan, 1, 8, np.nan],
                 [4, 9, 6, np.nan, np.nan]],
                [[5, np.nan, np.nan, 7, 2],
                 [3, np.nan, 1, 8, np.nan],
                 [4, 9, 6, np.nan, np.nan]],
                [[5, np.nan, np.nan, 7, 2],
                 [3, np.nan, 1, 8, np.nan],
                 [4, 9, 6, np.nan, np.nan]]])

print(f"arr 的shape为: {arr.shape}")

arr 的shape为: (4, 3, 5)


In [4]:
np.isnan(arr)

array([[[False,  True,  True, False, False],
        [False,  True, False, False,  True],
        [False, False, False,  True,  True]],

       [[False,  True,  True, False, False],
        [False,  True, False, False,  True],
        [False, False, False,  True,  True]],

       [[False,  True,  True, False, False],
        [False,  True, False, False,  True],
        [False, False, False,  True,  True]],

       [[False,  True,  True, False, False],
        [False,  True, False, False,  True],
        [False, False, False,  True,  True]]])

In [5]:
np.isnan(arr).shape

(4, 3, 5)

In [10]:
np.array([True, False]).astype('int')

array([1, 0])

In [11]:
np.array([True, False]).sum()

1

In [12]:
np.isnan(arr).sum(axis=0)

array([[0, 4, 4, 0, 0],
       [0, 4, 0, 0, 4],
       [0, 0, 0, 4, 4]])