### 计算两个向量的欧式距离
参考链接：
1. https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy
2. https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html
3. https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html

In [1]:
from scipy.spatial import distance
import numpy as np 

In [30]:
dataa = np.random.randint(0, 20, (5, 2))
datab = np.random.randint(0, 20, (3, 2))

In [31]:
dataa

array([[12,  2],
       [18, 17],
       [11, 13],
       [12, 11],
       [ 0, 17]])

In [32]:
datab

array([[15, 13],
       [ 1, 15],
       [ 0,  1]])

我们如果想计算dataa和datab的第一行数据的欧式距离，就可以这么写

原因是：
1. `np.linalg.norm`也就是常说的范数，默认是2阶的。
2. 那么`a - b`再用二阶范数，即可求出欧式距离。

In [33]:
dist = np.linalg.norm(dataa[0, :] - datab[0,:])
dist

11.40175425099138

但是有时候，要计算的都是成对成对计算的。这个时候，再简单的使用`np.linalg.norm`就不行了。这个时候可以使用下面的方法
需要注意的是：
1. dataa的维度是(5, 2)，其中5位于第0个位置，2位于第1个位置。第0个位置叫batch。第1个位置叫dimension。
2. 那么`distance.cdist`在计算的时候，都是保留batch上的维度。dimension维度都被计算消化掉了。

In [34]:
distance.cdist(dataa, datab, 'euclidean') #> 这里计算得到的维度是5x3，其中第一个5是dataa的batch，第二个3是datab的batch。

array([[11.40175425, 17.02938637, 12.04159458],
       [ 5.        , 17.11724277, 24.08318916],
       [ 4.        , 10.19803903, 16.2788206 ],
       [ 3.60555128, 11.70469991, 15.62049935],
       [15.5241747 ,  2.23606798, 16.        ]])