### 按照矩阵的某一列对矩阵排序
1. https://stackoverflow.com/questions/2828059/sorting-arrays-in-numpy-by-column


当前的矩阵是：
```
a = array([[9, 2, 3],
           [4, 5, 6],
           [7, 0, 5]])
```
希望对a的第二列排序，得到这样的结果
```
array([[7, 0, 5],
       [9, 2, 3],
       [4, 5, 6]])
```

In [1]:
import numpy as np
a = np.array([[9, 2, 3],
           [4, 5, 6],
           [7, 0, 5]])
a

array([[9, 2, 3],
       [4, 5, 6],
       [7, 0, 5]])

In [5]:
# 方法：

a[a[:, 1].argsort(), :]

array([[7, 0, 5],
       [9, 2, 3],
       [4, 5, 6]])

In [6]:
# step1 取出a的第二列
a[:, 1]

array([2, 5, 0])

In [7]:
# step 2 对a的第二列排序,
# 得到的索引，索引对应的值是从小达到排序的。
# 比如下面返回的2在第一个，因为index=2对应的值为0，最小。
# index=0对应的值为2，第二小
# index=1对应的值为5，最大
a[:, 1].argsort()

array([2, 0, 1])

In [8]:
# step3，把索引用在a上面
a[a[:, 1].argsort(), :] # -> 简写成a[a[:, 1].argsort()]也是可以的

array([[7, 0, 5],
       [9, 2, 3],
       [4, 5, 6]])